# This is a YAML-formatted file.
# Declare Variables to be passed into the templates.

deploymentName: cards-deployment
serviceName: cards
appLabel: cards
appName: cards

replicaCount: 1

image:
  repository: princejain1198/cards
  tag: s17

containerPort: 9000

service:
  type: ClusterIP
  port: 9000
  targetPort: 9000

appname_enabled: true
profile_enabled: true
config_enabled: true
discovery_enabled: true
resourceserver_enabled: false
otel_enabled: true
kafka_enabled: false


